### PR TITLE
Simplify qw25q

### PR DESCRIPTION
**Pull request by AleCandido**
If you wish, this is just a personal game: I want to see how simple we can trim down the most complex platform that we have.

My hope is that, playing this game, we might design useful abstractions, that can be lifted to Qibolab as building blocks (as it happened for the `ChannelMap`, that looks quite clean to me, despite being just a thin wrapper around a `dict`).

### CODE REVIEW

**Comment by AleCandido** [comment]
@DavidSarlle in this way, we could also move towards a more declarative approach, in the sense that if we have repeated patterns, we just need to specify the parameters of these patterns, passing them to suitable functions.

If in the end everything will be covered by suitable building blocks, then we can eventually collect back the parameters, and even avoid the Python file at all.
But for the time being, it is much simpler to use the flexibility of a GP language, rather than creating our own.

**Comment by DavidSarlle** [comment]
Thank you, @AleCandido , for your comments. From my point of view, it is clear that all setups in different laboratories have repeated patterns. The difference lies in the instrumentation used. For this reason, in my opinion, the Platform could be composed (as it already does with the new approach, but with the added capability of interpreting external configuration data, whether it's in YAML, a database, or any other system) of an instrument controller (a generic controller capable of controlling any supported instrument), the class that handles connections (channel/channelMap), and the qubits class. This is the most dynamic approach that facilitates the inclusion of new labs/users. It also ensures that adding new instruments does not require modifying any part of the qibolab or qibocal code, thereby simplifying the amount of code to maintain (there is now a new repository with one file per setup and one per runcard).

Additionally, it's important to consider that users who are using qibolab for the first time in their laboratory are experimental teams or chip manufacturers who generally do not have deep knowledge of programming or system administration. That's why avoiding the need to modify/create Python files is a great advantage for them. For example, the Boulos team, who do not know how to program, feels much more comfortable with the idea of configuring the lab setup by filling out a config template (similar to the qw5q_qblox_runcard). Their ideal scenario would even be to perform this configuration through a graphical interface. That would be great for them.

Regarding the other decisions (not mixing physical parameters and setup configuration in the same runcard, not having code linked to a specific laboratory in the repo...), I completely agree.

For all these reasons and with the premise of allowing users to focus even more easily on high-level concepts, I still think this approach would be more appropriate. But if others see it differently, there is no problem on my side, of course!

So once again, thank you for the explanations.

**Comment by stavros11** [comment]
Something possibly related to this discussion that came up while trying to refactor the `MultiqubitPlatform`, is the `instruments` section in the qblox runcards. Since we are moving to the declarative approach where we have a `create` method for each platform, instruments will be initialized there. However, the instrument settings https://github.com/qiboteam/qibolab_platforms_qrc/blob/55f80d03525ca3497dcb4cc4fb578156503384e5/qw5q_gold.yml#L78

should be stored in the runcard/database, so that we can track potential changes during calibration. Therefore we need a mechanism to load these settings and set the instruments appropriately. This may look different depending on what instruments are used. The `Channel` described in https://github.com/qiboteam/qibolab/issues/429#issuecomment-1568552130 could be responsible for that, however I do not think that it is a good place to store such parameters, because there are instruments (eg. local oscillators) that are shared between different channels, so storing instrument settings in the channels may lead to repetition and bugs.

**Comment by AleCandido** [comment]
Since they are `Instrument`s parameters, the `AbstractInstrument` itself (that btw I'd propose to rename just `Instrument`) could define the API for this:

```py
@dataclass
class InstrumentConfigs:
    """To be optionally subclassed by various instruments.

    It should not contain any method, that should be defined in :cls:`Instrument`,
    but rather just declare the tunable parameters.

    """

@dataclass
class Instrument:
    configs: InstrumentConfigs

    def setup(self):
        self.load(self.configs)

# Just a sketchy example, we should have a look at actual ones
```

**Comment by AleCandido** [comment]
> For this reason, in my opinion, the Platform could be composed (as it already does with the new approach, but with the added capability of interpreting external configuration data, whether it's in YAML, a database, or any other system) of an instrument controller (a generic controller capable of controlling any supported instrument), the class that handles connections (channel/channelMap), and the qubits class. This is the most dynamic approach that facilitates the inclusion of new labs/users. It also ensures that adding new instruments does not require modifying any part of the qibolab or qibocal code, thereby simplifying the amount of code to maintain.

@DavidSarlle about this I quite agree with you. My present opinion is that getting there in a single shot is complex, because we need some time to abstract differences and create sensible APIs to handle all of them.
Moreover, I perfectly agree that the parameters should be stored separately and declaratively, and for this reason I'm working on the DB.
However, some parts of the setup are really working bad declaratively, as the channels: if you have 25 qubits then you might have 25*4 channels. With more qubits they would grow even more, and we'd all start programming our editors to edit those files. Alternatively we would create a syntax in YAML for making loops (well, if sufficiently restrictive, it might be sensible, but not as the first attempt).

> (there is now a new repository with one file per setup and one per runcard)

Well, runcards were already there, we just moved mainly to separate PRs about runcards from PRs about code (and they will eventually fit in the DB), and the goal of this PR is to trim the setup-file more and more.

> Additionally, it's important to consider that users who are using qibolab for the first time in their laboratory are experimental teams or chip manufacturers who generally do not have deep knowledge of programming or system administration. That's why avoiding the need to modify/create Python files is a great advantage for them. For example, the Boulos team, who do not know how to code, feels much more comfortable with the idea of configuring the lab setup by filling out a config template (similar to the qw5q_qblox_runcard). Their ideal scenario would even be to perform this configuration through a graphical interface. That would be great for them.

As said above: this is a lot of work, because if you want to scale, you should allow to algorithmically set channels (e.g.) with a graphical tool.
I'm not saying we will never want this, but we just don't have the manpower to do it now. So let's allow for some flexibility, at no expense.
To support Boulos, it's easier to help him write a tiny `create_` function, rather than creating a specific syntax in YAML.

However, if we're good enough to extract patterns from the `create_` such that they can fit in a declarative format, and still scale, so much the better.
My starting point would be to just simplify `create_`, but if you prefer following a different route I'm open to discussion and proposals.

**Comment by scarrazza** [comment]
Shall we close this?

**Comment by DavidSarlle** [comment]
yes, we can close it @scarrazza

**Pull request closed without merging**
