### PR TITLE
Re-calibration for tii1q_b1

### PR DESCRIPTION
**Pull request by rodolfocarobene**
@MatteoRobbiati, I am not getting an optimal Ramsey nor an optimal RB, but for short circuits it should be good enough :-)

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
> Shuld I use some specific branch of the packages @rodolfocarobene? I am getting this error:
> 
> ```
>   File "/home/xilinx/qibosoq/src/qibosoq/rfsoc_server.py", line 96, in execute_program
>     average=data["cfg"]["average"],
> KeyError: 'average'
> ```

It seems like an error related to qibosoq, perhaps you are using an outdated version.
I would suggest to try to reinstall qibolab to see if this fixes the issue.

**Comment by rodolfocarobene** [comment]
> Shuld I use some specific branch of the packages @rodolfocarobene? I am getting this error:

Yes sorry, I forgot to tell you: you need a specific branch of qibolab (rfsoc-fixes) and qibosoq (fixes)...

**Comment by MatteoRobbiati** [comment]
> > Shuld I use some specific branch of the packages @rodolfocarobene? I am getting this error:
> > ```
> >   File "/home/xilinx/qibosoq/src/qibosoq/rfsoc_server.py", line 96, in execute_program
> >     average=data["cfg"]["average"],
> > KeyError: 'average'
> > ```
> 
> It seems like an error related to qibosoq, perhaps you are using an outdated version. I would suggest to try to reinstall qibolab to see if this fixes the issue.

**Comment by MatteoRobbiati** [comment]
Oh, sorry @rodolfocarobene! I close it by mistake :(

Thanks, I will use those branches.

**Pull request merged**
