### PR TITLE
Prefix service folders with underscore

### PR DESCRIPTION
**Pull request by alecandido**
To separate them from the runcards folders.

### CODE REVIEW

**Comment by alecandido** [comment]
@scarrazza I updated the workflows accordingly, but the monitoring tool will have to be updated as well.

**Comment by scarrazza** [comment]
@alecandido no problem, we keep the monitoring tool on hold until this, qibolab and qibocal are operative with the new structure.

**Comment by alecandido** [comment]
> I think I like the `qpus` folder option from [#108 (comment)](https://github.com/qiboteam/qibolab_platforms_qrc/pull/108#issuecomment-1911666060) a bit more, but anything that works is fine.

My motivation to avoid the `qpus` folder was to skip one extra layer, since this is already meant to be the example for how to write runcards. It's just that we need some extra content for our own management.

However, if you have arguments in favor of `qpus`, we could even go for that.

**Comment by andrea-pasquale** [comment]
> > I think I like the `qpus` folder option from [#108 (comment)](https://github.com/qiboteam/qibolab_platforms_qrc/pull/108#issuecomment-1911666060) a bit more, but anything that works is fine.
> 
> My motivation to avoid the `qpus` folder was to skip one extra layer, since this is already meant to be the example for how to write runcards. It's just that we need some extra content for our own management.
> 
> However, if you have arguments in favor of `qpus`, we could even go for that.

I am not sure about folders with `_` but I agree with the fact another layer like `qpus` is probably redundant

**Review by stavros11 — APPROVED** [review]
Since most people prefer the current structure I think we can merge this. Just to make sure, the `_` is only for cosmetic reasons, ie. to easily distinguish actual platforms from utilities, right?

**Comment by alecandido** [comment]
> Just to make sure, the `_` is only for cosmetic reasons, ie. to easily distinguish actual platforms from utilities, right?

Exactly, such that the file system and similar interfaces will sort them separately.

**Review by andrea-pasquale — APPROVED** [review]

**Pull request merged**
