### PR TITLE
Single qubit in XLD1000 controlled with QM

### PR DESCRIPTION
**Pull request by stavros11**
Works only for `octaves` qibolab branch qiboteam/qibolab#733

### CODE REVIEW

**Comment by igres26** [comment]
Calibration as of 16/02/2024

Some details:

- Spectroscopies work fine. 
- Rabi works fine
- T1 and T2 seem to have deteriorated since last scan.
- Ramsey fit sometimes fails, and if it doesn't it gives the corrected frequency wrong. Adds the delta the other way. 
- Flipping fit is prone to fail as well. 
- Flipping needs unrolling support.
- Single shot classification has improved, but still need to be better.
- Time of flight doesn't give useful results as it is now. 
- Introduce integration parameters. 
- Randomized benchmarking works fast in the `qmfastrb` branch of qibolab. Fails for 100 depth circuits.
- Using this branch, I get significantly worse results in rb. 0.93 down from 0.99 (might be decrease in T1 and T2 or something to do with the new implementation)

Please add in the pull request issues that you find as you calibrate. 

I will assign people so that I want aware of this branch and/or the problems that come up.

**Comment by andrea-pasquale** [comment]
> * Ramsey fit sometimes fails, and if it doesn't it gives the corrected frequency wrong. Adds the delta the other way.

Delta is wrong both for qblox and qm?

**Comment by stavros11** [comment]
Thanks @igres26 for the summary. Some quick updates:

> * T1 and T2 seem to have deteriorated since last scan.

We have been monitoring these (and assignment fidelity) over the whole weekend and they generally vary a lot.

> * Time of flight doesn't give useful results as it is now.

I tried this routine on a loopback (without qubit) and it gives a clear result:

http://login.qrccluster.com:9000/6B3nSop3TE2efnu6li0Lvg==

If you want to give a try you can change con1,octave1 -> con3,octave3 in the platform.py and (parameters.json) here. I have connected the output 1 to input 1 in octave3 in the lab. Also set the time of flight to 24 (minimum accepted by QM), otherwise you might miss the peak. 

If you also set `nshots: 1` when running the routine you can see the signal. For nshots > 1 it averages and it goes back to 0 (I am not sure why), but for loopback you can still see a peak.

I don't know why we only see noise when doing it with the qubit.

> * Introduce integration parameters.

In principle the drivers supports them and I pushed an example (using just `np.ones`) here which seems to work, but for now I have it commented out. I am not sure if we can calibrate them unless we resolve the issue with TOF though (@Jacfomg).

> * Randomized benchmarking works fast in the `qmfastrb` branch of qibolab. Fails for 100 depth circuits.

I pushed some updates on this and now it supports batches and is able to do depth 100. Try to pull the latest of `qmfastrb`. Btw, this is a bit experimental and as it is now only works for single-qubit, so I am not planning to open a PR.

> * Using this branch, I get significantly worse results in rb. 0.93 down from 0.99 (might be decrease in T1 and T2 or something to do with the new implementation)

I also fixed an issue with a missing `align` in the `qmfastrb`. I am not sure if that was causing this discrepancy because the qubit has been doing some crazy stuff when I was testing. The scheduling in the simulator looks fine in the `qmfastrb` branch though.

**Comment by igres26** [comment]
Further updates.

The Ramsey detuned is still giving trouble. I would even suggest, dropping the phase detuning for an actual frequency detuning, as it seems way more consistent. And if we fully control the direction we are detuning the frequency we will know how to properly correct it better. I did some tries with 1 GHz detuning, and the fit was returning the detuning in the wrong direction still. This will also help the autocalibration effort.

**Comment by andrea-pasquale** [comment]
> Further updates.
> 
> The Ramsey detuned is still giving trouble. I would even suggest, dropping the phase detuning for an actual frequency detuning, as it seems way more consistent. And if we fully control the direction we are detuning the frequency we will know how to properly correct it better. I did some tries with 1 GHz detuning, and the fit was returning the detuning in the wrong direction still. This will also help the autocalibration effort.

Thanks @igres26 for the update.
Concerning Ramsey I just opened a draft PR https://github.com/qiboteam/qibocal/pull/721 where I implemented the frequency detuning, I still need to test on hardware and check the sign of the frequency correction. 


> * Flipping fit is prone to fail as well.

Feel free to share any report where you see the fit failing so that we can improve it.

**Comment by igres26** [comment]
> > Further updates.
> > The Ramsey detuned is still giving trouble. I would even suggest, dropping the phase detuning for an actual frequency detuning, as it seems way more consistent. And if we fully control the direction we are detuning the frequency we will know how to properly correct it better. I did some tries with 1 GHz detuning, and the fit was returning the detuning in the wrong direction still. This will also help the autocalibration effort.
> 
> Thanks @igres26 for the update. Concerning Ramsey I just opened a draft PR [qiboteam/qibocal#721](https://github.com/qiboteam/qibocal/pull/721) where I implemented the frequency detuning, I still need to test on hardware and check the sign of the frequency correction.
> 
> > * Flipping fit is prone to fail as well.
> 
> Feel free to share any report where you see the fit failing so that we can improve it.

I will take a look thanks! I will try to reproduce failing fits and share the reports somehow. 
I remember also spin-echo used to fail.

If we knowingly detune the frequency by 1 GHz in a direction, then we know in which direction the detuning has happened, as it will be a correction over the manual one. And rarely it will be of over 2 GHz.

**Comment by igres26** [comment]
Latest calibration up. The devices will probably be disconnected tomorrow, so test away everything that is quantum machines dependent.

**Comment by igres26** [comment]
New calibration as of today. The hiccup on Friday was due to the extra thermalization time that the actual cavity has to go through even though the fridge is at base temperature. Some new issues on qibocal popped up, mostly due to fitting. I suspect this is due to trying to incorporate errors into the signal experiments.

The fits for the spectroscopies now show up, but don't fit properly. 

The fits for the following routines DO NOT show up anymore:
- Rabi
- T1
- T2
- flipping

Those are the ones I found. Ramsey with the new detuning seems to work well. 

Another small note, the punch out looks a bit strange, and might make you choose a too small an aptitude to the get good single shot classification.

**Comment by andrea-pasquale** [comment]
Thanks @igres26, for the update.
Regarding spectroscopies I've already fixed them in https://github.com/qiboteam/qibocal/pull/742 there was a small problem only in the report. 

For the other fits please share with me the reports generated by qibocal and I can have a look. 
Be aware that we recently merged https://github.com/qiboteam/qibocal/pull/707 which will not store failed fitting attempt to file anymore. Most likely what is going is that the fitting are failing and this is why you are not seeing them in the report...
Do the acquired data look reasonable?

**Comment by alecandido** [comment]
> Be aware that we recently merged [qiboteam/qibocal#707](https://github.com/qiboteam/qibocal/pull/707) which will not store failed fitting attempt to file anymore. Most likely what is going is that the fitting are failing and this is why you are not seeing them in the report...

Maybe we should write on the report that there has been an attempt, but it failed.

**Comment by andrea-pasquale** [comment]
> Thanks @igres26, for the update. Regarding spectroscopies I've already fixed them in [qiboteam/qibocal#742](https://github.com/qiboteam/qibocal/pull/742) there was a small problem only in the report.
> 
> For the other fits please share with me the reports generated by qibocal and I can have a look. Be aware that we recently merged [qiboteam/qibocal#707](https://github.com/qiboteam/qibocal/pull/707) which will not store failed fitting attempt to file anymore. Most likely what is going is that the fitting are failing and this is why you are not seeing them in the report... Do the acquired data look reasonable?

Nevermind @igres26, there was a problem introduced by me which I fixed in https://github.com/qiboteam/qibocal/pull/744.
To generate the proper report make sure to re-do the fit using
```sh
qq fit <output_folder>
```
 and to generate the new report
```sh
qq report <output_folder>
```

**Comment by stavros11** [comment]
Closing this because this chip is not available anymore. If it is needed in the future we can refer to this PR.

**Pull request closed without merging**
