### PR TITLE
Add SpinQ platform 

### LINKED ISSUE #92: Make SpinQ chip available
As discussed yesterday it would be nice to have also a runcard and a create method for the spinq chip.

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Closes #92 
This PR adds the SpinQ chip to the repository. Currently we don't care about the characterization but we just want to have another device where we can perform tests (especially 2 qubit gates).
@PiergiorgioButtarini whenever you have time could you update these files to the latest version of the driver?

### CODE REVIEW

**Comment by PiergiorgioButtarini** [comment]
This works only with the modification made in https://github.com/qiboteam/qibolab/tree/spinq_updated, since the last two qubit (9-10) are not physically connected to any flux line.
Other than being impossible to change the sweetspot for qubits 9-10, that is always at offset=0, the rest works fine.

**Comment by andrea-pasquale** [comment]
@PiergiorgioButtarini feel free to open a PR in qibolab for `spinq_updated` to see if we can merge the PR.

**Comment by PiergiorgioButtarini** [comment]
This is the relative qibolab PR https://github.com/qiboteam/qibolab/pull/703 that has to be merged first.

**Review by PiergiorgioButtarini — APPROVED** [review]

**Review by stavros11 — APPROVED** [review]
Thanks @andrea-pasquale. 
I don't think the chip is properly calibrated in this version of the runcard as most resonator frequencies are not set properly (http://login.qrccluster.com:9000/lTSfxqIYTc6M8UHnfy645g==) and also most of the qubits are not there (http://login.qrccluster.com:9000/jwSgWCJ3RQ2VGw2AKRTVhA==). Still better than nothing since it seems to work.

**Comment by andrea-pasquale** [comment]
Thanks for the review @stavros11.
Indeed I just wanted to make the runcard and the create method available for anyone.
As soon as we merge https://github.com/qiboteam/qibolab/pull/703 I will merge this PR to main.

**Comment by stavros11** [comment]
> 10: 0.477

So apparently the assignment fidelity can be <0.5.

**Pull request merged**
