### PR TITLE
Change name Qblox module classes

### PR DESCRIPTION
**Pull request by PiergiorgioButtarini**
This PR is needed to work with https://github.com/qiboteam/qibolab/pull/766.

### CODE REVIEW

**Review by alecandido — APPROVED** [review]

**Comment by PiergiorgioButtarini** [comment]
@stavros11  can you please approve this? Because I merged the relative qibolab PR.

**Review by stavros11 — APPROVED** [review]
I wanted to check if CI is passing with main after merging the other one but apparently is failing for a reason unrelated to the rename. So if you like merge this and we can fix in a new one, or fix directly here.

**Comment by PiergiorgioButtarini** [comment]
Yes I prefer to merge this and solve the problem in other PR.

**Comment by stavros11** [comment]
I am not sure if this is worth merging at this stage because #108 is duplicating the rename change and we will create unwanted conflicts.

**Comment by PiergiorgioButtarini** [comment]
Oh ok I see, I this point let's wait.

**Comment by andrea-pasquale** [comment]
Closing this since this change is already in #108

**Pull request closed without merging**
