### PR TITLE
B1-B3 CZ Gate

### PR DESCRIPTION
**Pull request by HishamKazim**
This PR is based on the calibration of B1-B3 using the Chevron, virtual Z, and CHSH experiments. 

1- Chevron: http://login.qrccluster.com:9000/n6Yl2wkNS1WkEY1ifTKS-Q==/
2- Virtual Z: http://login.qrccluster.com:9000/GhkVUQxuTyepEtwcWgF-QQ==/
3- CHSH Pulses: http://login.qrccluster.com:9000/WPLE0h22TGSJb9ynR70azg==/

### CODE REVIEW

**Review by hay-k — APPROVED** [review]

**Review by stavros11 — APPROVED** [review]

**Review by scarrazza — COMMENTED** [review]
@HishamKazim, thanks a lot for this. Does the README require changes?

**Comment by hay-k** [comment]
> @HishamKazim, thanks a lot for this. Does the README require changes?

I guess a new table like this could be added to the README:

| Pair | Calibrated gate | RB fidelity |
|-|-|-|
| B1-B3 | CZ | Not measured  |

**Comment by scarrazza** [comment]
Yes, that’s a good idea so we can keep track of 2q gates.

**Comment by HishamKazim** [comment]
@scarrazza Done, added it on the readme, as we get more results we can update the table.

**Comment by scarrazza** [comment]
@HishamKazim, perfect. Please go ahead and merge.

**Pull request merged**
