### PR TITLE
Update runcards to new layout

### PR DESCRIPTION
**Pull request by stavros11**
Makes runcards compatible with qiboteam/qibolab#525. Because the platform will no longer be "aware" of the runcard yaml, qubit and pair objects should be created in the `create` methods. We provide some utility functions (`qibolab.utils`) to assist with these creations and avoid code repetition. The procedure for writing a platform is described in [an example](https://github.com/qiboteam/qibolab/blob/07cc65142eb1726d9c914b2d362e449f4396f326/doc/source/code-examples/basic.rst#how-to-define-a-platform-for-a-self-hosted-qpu) which will eventually be part of qibolab documentation.

Some other key differences with before are:
* the `settings` section of the runcard should comply with the `PlatformSettings` object of qibolab. time of flight and smearing are no longer part of this because I saw that most of our platforms are setting these to the instruments directly.
* `platform.instruments` used to be a list but is now a dictionary `{instrument.name: instrument}` to be symmetric with the `platform.qubits` and `platform.pairs` dictionaries.

I have only ran some autocalibration with tii1q_b1 and qpu pytests with qw5q_gold_qblox. The rest of the platforms has not been tested yet. I will try to test all in the next days but let me know if you also give a try.

### CODE REVIEW

**Review by andrea-pasquale — APPROVED** [review]
Thanks @stavros11.
I tested this branch with qblox and everything seems to work as expected.

**Comment by scarrazza** [comment]
@stavros11 shall we merge this now and test carefully before the release?

**Comment by stavros11** [comment]
> @stavros11 shall we merge this now and test carefully before the release?

Sure, I agree with this plan. I have tested tii1q_b1 including some autocalibration and qw25qB (QM) using the runcard from the other branch. We should also test the IQM and ZCU platforms.

**Comment by AleCandido** [comment]
To automate a minimal part of these tests, I added #44

**Review by scarrazza — APPROVED** [review]

**Review by rodolfocarobene — APPROVED** [review]
I tested it with the zcu216 and it is working

**Comment by stavros11** [comment]
> I tested it with the zcu216 and it is working

Thanks! I am waiting for qiboteam/qibolab#563 to be merged to that I rename `qibolab.utils`->`qibolab.serialize` here and then I will merge.

**Pull request merged**
