### PR TITLE
Latest runcard qw5q_qblox

### PR DESCRIPTION
**Pull request by PiergiorgioButtarini**
The runcard is working but is not fully calibrated.

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
Qubits 1,3,4 at 80% fidelity

**Comment by andrea-pasquale** [comment]
Latest calibration:
http://login.qrccluster.com:9000/M5Fzi-iVSVeqyqb_4pKKBw==/

Current assignment fidelities:

- q0: 0.796
- q1: 0.911
- q2: 0.855
- q3: 0.906
- q4: 0.811

**Comment by andrea-pasquale** [comment]
@PiergiorgioButtarini feel free to check if you can reproduce the same results.
If you agree we can start merging this PR so that we have at least a decent calibration in main

**Comment by PiergiorgioButtarini** [comment]
Yes I agree to merge this. I checked and I obtain the following fidelities:

- q0: 0.787
- q1: 0.919
- q2: 0.863
- q3: 0.928
- q4: 0.829

Thanks @andrea-pasquale for the calibration.

**Review by andrea-pasquale — APPROVED** [review]

**Review by stavros11 — APPROVED** [review]
I agree, please go ahead with merging.

**Pull request merged**
