### PR TITLE
qw5q_platinum controlled with QM

### PR DESCRIPTION
**Pull request by stavros11**
Resonator spectroscopy (low power): http://login.qrccluster.com:9000/mlMEgtszR-WK9wxMGOXyYQ==
Punchout: http://login.qrccluster.com:9000/fZ7asJ3STau3tD8QiZ_cOA==
Resonator flux: http://login.qrccluster.com:9000/cPfzrZKGR8WtarCnbb7HCQ==

We may not be able to reach the sweetspot of qubit 4 without amplifier as it is around 0.5.

In a preliminary qubit spectroscopy we could not see qubit 2: http://login.qrccluster.com:9000/bHAvdYXgS6e0cFBEg8iGkA==

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
Thanks @stavros11, that's great.

For spectroscopies related experiments feel free to have a look at https://github.com/qiboteam/qibocal/pull/744 (which fixes the $\chi^2$) and at https://github.com/qiboteam/qibocal/pull/742 (which fixes the fitted plot).

**Comment by igres26** [comment]
Small update on the 5 qubit chip calibration:

There has been some problems on some of the qubits. The power of some of the lines are very different, and that is causing problems. It might be due to some of the lines being damaged, or not properly connected. I have seen this most in the drive lines for qubit 0 and 2.

One of the main problems in this is the mixer calibration. IF the mixer is not properly set up, we get really bad results. We are working on new mixer calibration with Stavros.

Qubit 0:
- Frequency found and sweet spot found.
- Needs very high power! 20 gain on quantum machines
- Best performing qubit of the bunch.
- T1 ~ 42micro
- T2 ~ 11micro
- T2echo ~21micro
- Assignment Fidelity ~.87
- RB decay parameter ~0.985

Qubit 1:
- Issues finding the qubit.
- A lot of crosstalk with qubit 0.

Qubit 2:
- Frequency found and sweet spot found.
- Needs maximum gain in order to get signal.
- Not enough power to get a PI pulse.

Qubit 3:
- Frequency found and sweet spot found.
- Needs less power -10 gain on quantum machines.
- Good performance, best in single shot.
- Can have some crosstalk with qubit 4.
- T1 ~ 28 micro
- T2 ~ 19micro
- T2echo ~ 24micro
- Assignment Fidelity ~.96
- RB decay parameter ~ 0.992

Qubit 4:
- Not enough flux to put on sweet spot. 
- Issues finding the qubit.


I will continue to improve this, but without control of qubit 2, two qubit gates are impossible. We should try and pinpoint why the change in power for the faulty lines, and if it is something we can fix without warming up the fridge.

**Comment by frederico-brito** [comment]
Hi Sergi,

Thanks for the update. All cables were double-checked just before the second cool-down, and they were working correctly. In addition, during the VNA characterization, they did not see any behavior that could signal broken lines. So, it seems unlikely that the lines are damaged, but we can check them again. 

Regarding crosstalk, during the VNA characterization, only qubit 3 was shown to affect the others. The conclusion was that this qubit has a stronger coupling, and we should use less power when operating it.  

How is the mixer calibration doing? If it is done and things do not improve, we can proceed with the lines double-checking again.

**Comment by stavros11** [comment]
> Qubit 2:

> * Needs maximum gain in order to get signal.

For qubit spectroscopy we were able to get it quite clear with the octave gain=0, pulse amplitude=0.5 and duration=2000. According to the lab guys, this gain/amplitude is matching the power levels they are using with the VNA.

> * Not enough power to get a PI pulse.

I was able to get a pi-pulse on qubit 2 using gain=20, amplitude=0.39, after parking qubit 1 at lower frequency (setting its sweetspot=-0.4 and recalibrating the qubit 2 sweetspot): http://login.qrccluster.com:9000/Q3Vvm6sfToehngAUFOeRuQ==/

The Rabi length looks kind of weird though (the minima look very flat but may be my impression): 
http://login.qrccluster.com:9000/HJ79S267R4-O82qaKqCivw==/
http://login.qrccluster.com:9000/Vel7cJ7ST1uAoZ2UUGGupw==/

**Comment by andrea-pasquale** [comment]
> The Rabi length looks kind of weird though (the minima look very flat but may be my impression):
> http://login.qrccluster.com:9000/HJ79S267R4-O82qaKqCivw==/
> http://login.qrccluster.com:9000/Vel7cJ7ST1uAoZ2UUGGupw==/

Thanks for the update @stavros11, I was curious about why the fitting failed and I discover that there was a bug in qibocal. If you check https://github.com/qiboteam/qibocal/pull/754 the bug should be fixed.
Here is an example with one of the report that you provided:
http://login.qrccluster.com:9000/cCshgZQpSfOVoHGdZ68TDQ==

**Comment by stavros11** [comment]
I pushed an update in the parameters with qubit 1 parked away from its sweetspot, which allows to do some Rabi on qubit 2. With that, I was able to get a pi-pulse on qubits 2, 3 and get assignment fidelities of 97% and 94% respectively:
* Rabi: http://login.qrccluster.com:9000/Trda5nj1SmqsnJKkmBMHVw==/
* Single shot: http://login.qrccluster.com:9000/YuMDUwRcTfG6KC65S7imfg==/

I have ignored the other qubits for the time being but maybe qubit 0 can still work. Qubits 1 and 4 probably no as they are not at the sweetspot.

Some other notes regarding this:
* In my runs I did not use any mixer calibration (I removed calibration_db.json but I didn't push the removal here). This was mainly because I was experimenting with it. Most it won't have any significant effect.
* We discovered that QM keeps LOs on forever after you use them once. This may affect things especially if the LOs are set at gain=20 because this power level may be comparable to the operating level of some other qubit. For now, I am turning LOs off manually with another script, but soon I will update the driver to do it automatically (I am planning to talk to QM about it first). The LOs of qubits 0, 1, 4 are currently off, if you never use them (for drive) they will remain off, but if you use them it may be good to turn them off after or set a low gain.

**Comment by igres26** [comment]
Update:

We focused on getting the calibration done for qubits 2 and 3. We managed to reach 2 qubit gates and perform a preliminary CHSH experiment. 

Some reports:

T1: http://login.qrccluster.com:9000/QBnzzClETxOQANqEVb6W2g==
Chevron: http://login.qrccluster.com:9000/6C-_3WGmRu2SLRVBHO3EUA==
CZ calibration: http://login.qrccluster.com:9000/kvvisGJtR1aHdLxn2AEpmA==
And CHSH: [bell_sweep_fig_long.pdf](https://github.com/qiboteam/qibolab_platforms_qrc/files/14665481/bell_sweep_fig_long.pdf)

We have now fixed the cables to account for the 3 internal LO's on QM. And are working on getting more qubits up to spec.

More updates soon.

**Comment by igres26** [comment]
New update:

Calibration of qubit 0 alongside the other two.

Qubit 0 has been brought up to spec with the other two, but there is still work to be done. Some results:

Qubit spectroscopies: http://login.qrccluster.com:9000/8EopsaYyS2ebjl2PJDoCzg==
Rabi: http://login.qrccluster.com:9000/-Sk20VgwRuS5k6_2dfD-0Q==
T1: http://login.qrccluster.com:9000/e3MFHGUrRYS7IpNqhnVGdw==
Chevron 02: http://login.qrccluster.com:9000/64CbSHZzQuGPTiIz2j31Qw==
CZ calibration 02: http://login.qrccluster.com:9000/ZCtYqIlvSPOWjz6QjIeHsw==
CHSH 02: [bell_sweep_fig_02.pdf](https://github.com/qiboteam/qibolab_platforms_qrc/files/14724179/bell_sweep_fig_02.pdf)


A preliminary Mermin gives around 1.9 without mitigation and around 2.4 using mitigation. The actual value should be 4, and larger than 2 means inherently quantum effects. The fact that readout error mitigation does not bring this much higher means that other sources of error are affecting significantly more than regular CHSH. Candidates: CZ calibration of BOTH 02 and 23 have to be better. Single qubit gates can be improved. The issue with T2 is still present, effects might start to be more apparent in longer circuits.

(Mermin code is in an old branch, Middleware is taking care of qibocalifying it and incorporating it into the pipeline)

TODO: Understand deterioration in T2. Fine tune calibration of single and two qubit gates and redo Mermin. Introduce qubits 1 and 4 to the mix. (ideally in that order)

**Comment by igres26** [comment]
Calibrated both two qubit gates at the same time. 

Flux Matrix: http://login.qrccluster.com:9000/ilbIJ7YLTju4I3sv0WXSDw==
CZ Landscapes: http://login.qrccluster.com:9000/DoIh0xG6RemJYQe-0IcRCA==

Successfully performed Mermin Experiment. With bare results we exceed the classical bound of 2.

Mermin Experiment results:

Value for Mermin inequlity found from experiment: 2.7734

Value for Mermin inequlity after readout error mitigation: 3.6112104348992164

Target value for Mermin inequality: 4.0

**Comment by aorgazf** [comment]
Hi @igres26,
were you able to run any T2?

**Comment by Edoardo-Pedicillo** [comment]
Small single qubit gates recalibration of qubits 0,2,3.
Allxys: http://login.qrccluster.com:9000/6ga4xS5KToeK8EY6NLGFIQ==/

RBs:

- qubit 2: http://login.qrccluster.com:9000/BYrSE1g0S8CMn5wA5s_RzA==/
- qubit 3: http://login.qrccluster.com:9000/cIpHYprpQkuojbRe3_YhKA==/

**Comment by andrea-pasquale** [comment]
> Small single qubit gates recalibration of qubits 0,2,3.
> 
> Allxys: http://login.qrccluster.com:9000/6ga4xS5KToeK8EY6NLGFIQ==/
> 
> 
> 
> RBs:
> 
> 
> 
> - qubit 2: http://login.qrccluster.com:9000/BYrSE1g0S8CMn5wA5s_RzA==/
> 
> - qubit 3: http://login.qrccluster.com:9000/cIpHYprpQkuojbRe3_YhKA==/

Nice! For single qubit did you also do drag calibration? The middle section of the allxy feels a bit too far from the expected value.

**Comment by Edoardo-Pedicillo** [comment]
> Nice! For single qubit did you also do drag calibration? The middle section of the allxy feels a bit too far from the expected value.

I tried with qubits 0 and 3, but I didn't notice a difference. Maybe the choice of the parameters were not optimal, I will retry.

**Comment by Edoardo-Pedicillo** [comment]
Drag pulses calibration:
- qubit 0: http://login.qrccluster.com:9000/Qz7dIsHQRjSEs8agnS9mjw==/
- qubit 2: http://login.qrccluster.com:9000/vheiZ3xhR4GqFSXlSgsNJA==/
- qubit 3: http://login.qrccluster.com:9000/izzCfcprTWqPdN1idHimpQ==/

**Comment by andrea-pasquale** [comment]
@stavros11 I see that there is a TWPA but I see no channel with the TWPA (like we did for example here https://github.com/qiboteam/qibolab_platforms_qrc/blob/70ec2880a59872eb0f467712df9f756bf1d8531c/qw5q_gold/platform.py#L78-L80). Tatiana was trying to run some twpa calibration protocols and she saw an error of the type `None` has no attribute local_oscillator.
Is this expected?

**Comment by stavros11** [comment]
> ). Tatiana was trying to run some twpa calibration protocols and she saw an error of the type `None` has no attribute local_oscillator.
> Is this expected?

Indeed, the TWPA channel was missing. I added it in 0321bb085acf71c0ab9ee919c82dde4a941fe615.
This was not causing any issues is other routines as the TWPA LO was still passed to the platform and therefore we were connecting and turning on the instrument. In the twpa calibration protocols you are probably trying to access the TWPA using
```py
qubit.twpa.local_oscillator
```
and this definition was missing. It should work now.

**Comment by andrea-pasquale** [comment]
> > ). Tatiana was trying to run some twpa calibration protocols and she saw an error of the type `None` has no attribute local_oscillator.
> > Is this expected?
> 
> Indeed, the TWPA channel was missing. I added it in [0321bb0](https://github.com/qiboteam/qibolab_platforms_qrc/commit/0321bb085acf71c0ab9ee919c82dde4a941fe615). This was not causing any issues in other routines as the TWPA LO was still passed to the platform and therefore we were connecting and turning on the instrument. In the twpa calibration protocols you are probably trying to access the TWPA using
> 
> ```python
> qubit.twpa.local_oscillator
> ```
> 
> and this definition was missing. It should work now.

Yes, this is the case for the TWPA protocols. Thanks!

**Comment by stavros11** [comment]
Superseded by #147.

**Pull request closed without merging**
