### PR TITLE
Alvaro/qw5q gold runcard 20231109 Initial characterisation after cooldown

### PR DESCRIPTION
**Pull request by aorgazf**
Assigment fidelities around 89%

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
Thanks @aorgazf. I just run a `readout_characterization` protocol to assess the quality of the runcard.
Here are the results: http://login.qrccluster.com:9000/qcJPR0cSStu718LJc9qw6A==/
The assignment fidelities with the current runcard are lower than 89% but we can start playing with this runcard for sure.

**Comment by aorgazf** [comment]
Hi @andrea-pasquale, yes I see similar results, I'm not sure why, but it could be due to the fact that the chip is still not cold. This has happened before, in the hours after reaching base temperature.
Additionally, there seems to be a slight problem with the XLD after the maintenance, and I Bluefors engineer and Varun are performing tests that are warming up the fridge a bit temporarily.

**Comment by stavros11** [comment]
Thanks for the runcard. Maybe we should wait for the temperature to stabilize and retry to get better fidelities before we merge.
On another note, we should consider renaming this to qw5q_gold (instead of qw5q_gold_qblox) to fix #74, as I believe it is also easier for the monitoring tool if the platform names are one-to-one with the slurm partitions. There is no qw5q_gold.py file on main anyway.

**Comment by stavros11** [comment]
Qibolab interface has been changed. Superseded by https://github.com/qiboteam/qibolab_platforms_qrc/pull/91.

**Pull request closed without merging**
