### PR TITLE
Calibration of B4

### PR DESCRIPTION
**Pull request by HishamKazim**
This PR focuses on the calibration of B4. The results of the calibration are shown below:

| Metric                | Value     | 
|-----------------------|-----------|
| Readout Fidelity      | 0.88     | 
| Assignment Fidelity    | 0.94     | 
| T1 (us)     | 14.3 ± 0.1    | 
| T2 (us)     | 18.2 ± 0.3    | 
| Gate Infidelity (e-3) | 8.5 ± 0.1  | 

Reports:
1- Resonator spectroscopy / Punchout: http://login.qrccluster.com:9000/rAP_Ed8XS9-42HudHnedvg==/
2- Qubit Flux: http://login.qrccluster.com:9000/YkV8sJMZTq2562jNRFiLpQ==/
3- Qubit Spectroscopy: http://login.qrccluster.com:9000/5vKdDyx7RXi6V9iK-Axinw==/
4- Rabi: http://login.qrccluster.com:9000/bdjkcszCTISdJOZW6irSEg==/
5- Results: http://login.qrccluster.com:9000/jZgN3ku1QGSsmARztVXgnw==/

### CODE REVIEW

**Comment by scarrazza** [comment]
@HishamKazim thanks for this. @stavros11 could we incorporate this line in your #195?

**Comment by scarrazza** [comment]
Btw, @HishamKazim, could you please update the README.md with B4? Thanks.

**Comment by HishamKazim** [comment]
@scarrazza Done I have updated it

**Comment by scarrazza** [comment]
Thanks @HishamKazim !

**Comment by scarrazza** [comment]
@stavros11 I would like to merge this now, are you able to integrate this in #195 from main?

**Comment by stavros11** [comment]
> @stavros11 I would like to merge this now, are you able to integrate this in #195 from main?

Yes, I just rebased #195 to the latest 0.1 branch. I just need to rerun the single shot routine, because #195 is modifying some of the filters for line D and this usually affects all thresholds and angles in the instrument.

**Pull request merged**
