### PR TITLE
Re characterization of iqm5

### PR DESCRIPTION
**Pull request by DavidSarlle**
Re characterization of iqm5

After fixing some grounding problems and detecting the flux crosstalk, the fidelities are increased:

q4: 
91% fidelity 

* Needs bias to be in the sweetspot that affects q3 and q2, decreasing the readout fidelities of thes qubits.
If you are using only q4, set the ss to the value in the runcard. If not, set it to 0.0

image

q3: 
91% fidelity
* Pi pulse of 60ns. Not possible to reach 40ns. already using amp 1 and higgest power in the drive line

image

q2
55% fidelity
* Really poor RO signal. Too noisy. If we decrease the RO power we can not see the qubit. At least, the qubit is there and behaves as a qubit, responding to the drive signal and the flux. 
[WIP] using it for 2q gates

q1:
86% fidelity
image

q0
73% fidelity

image

### CODE REVIEW

**Comment by DavidSarlle** [comment]
@aorgazf @andrea-pasquale @Edoardo-Pedicillo from my side this the better runcard that I can reach with the current platform.

**Comment by DavidSarlle** [comment]
All qubits has been recharacterized after the TWPA calibration done in the lab. Also the RO power has been reduced to avoid wird tails in classification gaussian distributions. 

q0:
Assfg. fidelity: 75%
T1: 12406 ns
T2: 250 ns

image


q1:
Assfg. fidelity: 70%
T1: 15030 ns
T2: 241 ns

image

q2:
Assfg. fidelity: 68%
T1: 7400 ns
T2: 2564 ns

image


q3:
Assfg. fidelity: 66%
T1: 11000 ns
T2: 740 ns

* not working well. With max drive power and mas amplitude, no pi pulse 40ns duration can be reached

image

image

q4:
Assfg. fidelity: 82%
T1: 5800 ns
T2: 366 ns

image

**Comment by stavros11** [comment]
@DavidSarlle @andrea-pasquale some PRs that were merged in qibolab earlier today may have caused some incompatibilities with the platforms here. These should be fixed in the current main, so if you merge again it should work. Sorry for any inconvenience and let me know if there are any issues.

**Comment by DavidSarlle** [comment]
@stavros @andrea-pasquale  I merged main into my branch and using qibolab main I get the error:

  File "/home/users/david.fuentes/qibolab_platforms_qrc/iqm5q.py", line 196, in create
    qubits, couplers, pairs = load_qubits(runcard, FOLDER)
  File "/nfs/users/david.fuentes/qibolab/src/qibolab/serialize.py", line 54, in load_qubits
    qubit.kernel_path = extras_folder / single_qubit[qubit.name]["kernel_path"]
KeyError: 'kernel_path'

**Comment by DavidSarlle** [comment]
> @Stavros @andrea-pasquale I merged main (up to date) into my branch and using qibolab main I get the error:
> 
> File "/home/users/david.fuentes/qibolab_platforms_qrc/iqm5q.py", line 196, in create qubits, couplers, pairs = load_qubits(runcard, FOLDER) File "/nfs/users/david.fuentes/qibolab/src/qibolab/serialize.py", line 54, in load_qubits qubit.kernel_path = extras_folder / single_qubit[qubit.name]["kernel_path"] KeyError: 'kernel_path'
> 
> I am using qibolab main and it is up to date

Problem fixed. There was some changes in main that were not merged into my branch because they were not detected by git. I do not why, but I added them manually and now it works with qibolab main and should contain the latest changes introduced in main

**Comment by stavros11** [comment]
Thanks @DavidSarlle. Should the current version behave like the plots in the first post or are any sweetspots changed? Because I just tried to run a single shot and allXY and the fidelities I get are much worse: http://login.qrccluster.com:9000/1DA_xNJXQTWF3D-vsO25ww==

**Comment by DavidSarlle** [comment]
> Thanks @DavidSarlle. Should the current version behave like the plots in the first post or are any sweetspots changed? Because I just tried to run a single shot and allXY and the fidelities I get are much worse: http://login.qrccluster.com:9000/1DA_xNJXQTWF3D-vsO25ww==

@stavros11 no. The runcard has some comments on how to operate it when we are running single qubit gates until we characterize the couplers. Until them, we can not set the coupler is the issolation point between qubits, and there is to much crasstalk tat reduces the fidelities and affects T1s.

Also, in the version that is in this branch, q2 sweetspot has the value that I am using for chracterizing coupler interaction. It should be set to the value that is commented indicateing "real ss":             
sweetspot: -0.096 #(real ss)
Same for all the qubits. 

Also q4 needs too much bias to be in the sweetspot and it affects the performance of the rest of the qubits. So, run single qubit gates in q4 alone. SAme for q2, but the RO is pretty bad, so do not expect good fidelity dor q2.

**Pull request closed without merging**
