### PR TITLE
qw5q_platinum calibration

### PR DESCRIPTION
**Pull request by DavidSarlle**
This runcard works with qibocal and qibolab main

q0, q2, q3, q4 single qubit gates calibrated. 
q1 not working

classify

q0 (95.1%): http://login.qrccluster.com:9000/mBBUumF3TUKeWdls4ueGDA==
q1: Qubit not working. 
q2 (95.4%): http://login.qrccluster.com:9000/jnNCfLMKTvuo-tuDHq3wVg== 
q3 (93.8%): http://login.qrccluster.com:9000/eXAUMIbwTkWlR9E9mgyWng==
q4 (93.7%): http://login.qrccluster.com:9000/uO9k8JQCSOCDtQu4Q3FjvQ== 

[WIP]: Running the following routines to fine tuning the qubits:

TWPA freq and pow
Drag pulse

### CODE REVIEW

**Review by andrea-pasquale — COMMENTED** [review]
Thanks @DavidSarlle.
I am getting an error probably due to the kernels file.
Removing it fixed the issue for me.

**Comment by DavidSarlle** [comment]
@andrea-pasquale I am running the runcard without problems... But if you fixed, perfect! Thanks!

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale I am running the runcard without problems... But if you fixed, perfect! Thanks!

I see, then probably there could be an issue on my side. I will check again. Thanks!

**Comment by DavidSarlle** [comment]
@andrea-pasquale seems a problem with the laboneq software from ZI. I am using a fresh venv with qibolab and qibocal main without errors. I am using this version:

imagen

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale seems a problem with the laboneq software from ZI. I am using a fresh venv with qibolab and qibocal main without errors. I am using this version:
> 
> imagen

Thanks for sharing I am currently using the same `labone` and `laboneq` versions.
Any clues about this @hay-k?

**Comment by hay-k** [comment]
@andrea-pasquale are you running an experiment with more than one measurement in a single sequence? I am not sure why this error is happening, but will take a look. My hunch tells me it is caused by a floating point error somewhere, or it is just a bug either in our driver or in laboneq.

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale are you running an experiment with more than one measurement in a single sequence? 

Yes, I'm running the following runcard
```yaml
targets: [0, 2, 3, 4]

actions:

  - id: readout characterization
    operation: readout_characterization
    parameters:
      nshots: 5000
      delay: 2000
```
which involves two measurements on a single sequence.
This is usually what we use for monitoring the chip without updating the single shot classification parameters.

> I am not sure why this error is happening, but will take a look. My hunch tells me it is caused by a floating point error somewhere, or it is just a bug either in our driver or in laboneq.

Thanks for the explanation. If we see that the fix is not trivial (or it is in laboneq) I would suggest to merge #168.

**Comment by hay-k** [comment]
I believe the kernel file can be removed (i.e. https://github.com/qiboteam/qibolab_platforms_qrc/pull/168 merged) regardless. I am the one who originally created this platform using ZI instruments, and I just carried over the kernel file from previous version of the setup. It contains kernel for qubit 0 only. I believe none of the people calibrating so far have used or calibrated kernels, so the file just contains old information and is misleading.

**Review by andrea-pasquale — APPROVED** [review]
I suggest to merge this PR as soon as possible given that the platform on main is uncalibrated. For further calibration we can open new PR.

**Comment by DavidSarlle** [comment]
> I suggest to merge this PR as soon as possible given that the platform on main is uncalibrated. For further calibration we can open new PR.

@andrea-pasquale give me tonight and I will finish the fine tunning for all the qubits. Righ now only the drag and flipping is missing.

**Comment by DavidSarlle** [comment]
@andrea-pasquale @hay-k @biankawolo drag is not increasing fidelities. Runnign all qubits together with the current runcard, we get this fidelities:

http://login.qrccluster.com:9000/93sTli_jQUuLOCSzhtvprQ==

Seems that the crosstalks is not too much. I would merge the runcard in as it is. From there we can work for extra fine tunning (if possible) and in parallel, with the 2q gates

**Comment by andrea-pasquale** [comment]
> @andrea-pasquale @hay-k @biankawolo drag is not increasing fidelities. Runnign all qubits together with the current runcard, we get this fidelities:
> 
> 
> 
> http://login.qrccluster.com:9000/93sTli_jQUuLOCSzhtvprQ==
> 
> 
> 
> Seems that the crosstalks is not too much. I would merge the runcard in as it is. From there we can work for extra fine tunning (if possible) and in parallel, with the 2q gates

Thanks @DavidSarlle. Drag is not supposed to increase the readout fidelity. You should see improvements by running either RB or allXY. In any case let's merge :)

**Comment by DavidSarlle** [comment]
@andrea-pasquale you are right, sorry. My mistake, I wanted to say allXY :)

**Comment by DavidSarlle** [comment]
T1s: http://login.qrccluster.com:9000/p0VAFktxQPS8GwVXcqyNsg==

**Review by stavros11 — APPROVED** [review]
Approving so that you can merge ;)

> @andrea-pasquale @hay-k @biankawolo drag is not increasing fidelities. Runnign all qubits together with the current runcard, we get this fidelities:
> 
> http://login.qrccluster.com:9000/93sTli_jQUuLOCSzhtvprQ==

I have not tried to run anything, but slightly lowering the readout power for qubit 4 (and maybe 3) could reduce the "tail" of the excited state blob. At least this was the case for qw11q. It usually doesn't improve the fidelity that much though and the blobs may move a bit closer to each other.

**Review by biankawolo — APPROVED** [review]
We got there!

**Comment by biankawolo** [comment]
> Approving so that you can merge ;)
> 
> > @andrea-pasquale @hay-k @biankawolo drag is not increasing fidelities. Runnign all qubits together with the current runcard, we get this fidelities:
> > http://login.qrccluster.com:9000/93sTli_jQUuLOCSzhtvprQ==
> 
> I have not tried to run anything, but slightly lowering the readout power for qubit 4 (and maybe 3) could reduce the "tail" of the excited state blob. At least this was the case for qw11q. It usually doesn't improve the fidelity that much though and the blobs may move a bit closer to each other.

--- @ Everybody -Hey guys! this is just the first version. We r still working on that:) in platinum_zi there is a runcard where less power on readout is put  BUT drag and allxy are not done yet. Will be done tommorow. The fidelities are 94%for q0 95% for q2, 94% for q3 and 93+% for q4.  The blobs are more centralized though.  use whichever runcard you want or combine the two  for once-in-a-lifetime characterization experience! :)

**Comment by biankawolo** [comment]
Hello! again! also if you are testing routines could you please check  single shot sweep? it is supposed to give you the best MZ amplitude, but when you do the routine and choose the amplitude with the lowest probability error you actually get  the worst results. Could you please check? Thanx!

**Comment by andrea-pasquale** [comment]
> Hello! again! also if you are testing routines could you please check single shot sweep? it is supposed to give you the best MZ amplitude, but when you do the routine and choose the amplitude with the lowest probability error you actually get the worst results. Could you please check? Thanx!

There is already an issue about this: https://github.com/qiboteam/qibocal/issues/847
What that particular routine does is just changing the readout amplitude and running a single shot classification.
Increasing the power can lead to better fidelities at the price of losing the gaussian shape of the blobs. 
We suggest to perform short scans to avoid reaching that type of configuration where the blob are not gaussians, moreover if the difference is not much in fidelity it would be better to always choose the point with lower amplitude.
Ideally we could work on a fix that is testing also the shape of the blobs before assigning the best point.

**Comment by andrea-pasquale** [comment]
> But then the fidelities decreases when bobs stop being bloby, so after applying the result of the routine the fidelity is worst. I perform scans around 0.08 in amplitude. Which range would you suggest.:) then my concern is about single shot sweep not single shot as raced in the issue [qiboteam/qibocal#847](https://github.com/qiboteam/qibocal/issues/847). It is a different routine that doesn t show classification but chosses the optimal MZ amplitude:
> # - id: single shot sweep q0
> # priority: 0
> # targets: [0]
> # # main: allXY
> # operation: resonator_amplitude
> # parameters:
> # amplitude_start: 0.08
> # amplitude_stop: 0.28
> # amplitude_step: 0.01
> # nshots: 4024

As I already said the routine at the moment doesn't take into account the shape of the blobs, so if you run a large sweep and you see the fidelity increasing it's probably not the correct configuration. The parameter `amplitude_stop` is there to exactly to choose as maximum value a point where the blobs are not gaussians.
In your case, given that you know that they are not gaussian already, I would put the current value in the runcard as `amplitude_stop` and I will check if for lower amplitudes you get similar results.

**Comment by biankawolo** [comment]
but my blobs are circles - this is a correct shape right? So theroutine should work, or not?

**Comment by andrea-pasquale** [comment]
> but my blobs are circles - this is a correct shape right? So theroutine should work, or not?

Can you please share some data or upload the reports where you are seeing this weird behavior?

**Comment by biankawolo** [comment]
sure! just give me a minute!

**Comment by biankawolo** [comment]
Andrea are you in the office today? so after lunch , if you are free I can come and show you my concern, ok?

**Pull request merged**
