### PR TITLE
Drop offset setting Qblox 

### PR DESCRIPTION
**Pull request by PiergiorgioButtarini**
This PR is needed after merging https://github.com/qiboteam/qibolab/pull/686.

The offset setting, regarding modules Qcm_bb, was removed from the runcard yaml since this information is already provided by `qubit.sweetspot`.

### CODE REVIEW

**Comment by AleCandido** [comment]
Don't you need to remove also:
https://github.com/qiboteam/qibolab_platforms_qrc/blob/bddae914f89a87df0d5cc725f7465489f8958523/spinq10q.yml#L79-L101
?

**Review by stavros11 — APPROVED** [review]
> Don't you need to remove also:

Done. We should merge this asap, otherwise qblox does not work with the current main of qibolab.

**Comment by PiergiorgioButtarini** [comment]
Thanks @stavros11! Sorry @AleCandido I was in the lab and I forgot to address your comment.

**Review by AleCandido — APPROVED** [review]
> Thanks @stavros11! Sorry @AleCandido I was in the lab and I forgot to address your comment.

Never mind :)

**Pull request merged**
